### ISSUE TITLE
New name to something acceptable.

### ISSUE THREAD

**Issue by pinkrespect** [pinkrespect/maisie-memo#4]
At first I tried to do this project alone.
In order to make this project open source,
I thought I had to change the project's repository name to something acceptable to everyone.

If you have a name you would like to recommend, please write below this issue.

**Comment by winterjung** [comment]
How about `twitter-memo`?
It not only show explicitly what we do but also nobody used this name.

**Comment by pinkrespect** [comment]
It ends on June 19th.

**Comment by pinkrespect** [comment]
Changed name of project.

**Comment by pinkrespect** [comment]
Changed name of project.
